[versions]
# Build plugins
kotlin = "2.4.20"
dokka = "2.2.0"
mavenPublish = "0.37.0"
ktlint = "1.8.0"

# Libraries
gdx = "1.14.2"
gdxAi = "1.8.2"
ashley = "1.7.4"
artemisOdb = "2.3.0"
visUi = "1.5.9"
kotlinxCoroutines = "1.11.0"
assertj = "3.27.7"
mockitoKotlin = "6.3.0"
wireMock = "2.27.2"
slf4j = "2.0.18"
junit = "4.13.2"
spek = "1.1.5"
kotlintest = "2.0.7"
junitPlatformLauncher = "1.14.4"
freePortFinder = "1.0"
textraTypist = "2.4.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-scripting-common = { module = "org.jetbrains.kotlin:kotlin-scripting-common", version.ref = "kotlin" }
kotlin-scripting-jvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlin" }
kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinxCoroutines" }

gdx = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdx-box2d = { module = "com.badlogicgames.gdx:gdx-box2d", version.ref = "gdx" }
gdx-freetype = { module = "com.badlogicgames.gdx:gdx-freetype", version.ref = "gdx" }
gdx-ai = { module = "com.badlogicgames.gdx:gdx-ai", version.ref = "gdxAi" }
gdx-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdx" }
gdx-box2d-platform = { module = "com.badlogicgames.gdx:gdx-box2d-platform", version.ref = "gdx" }
gdx-freetype-platform = { module = "com.badlogicgames.gdx:gdx-freetype-platform", version.ref = "gdx" }
gdx-backend-headless = { module = "com.badlogicgames.gdx:gdx-backend-headless", version.ref = "gdx" }
gdx-backend-lwjgl = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl", version.ref = "gdx" }
gdx-backend-lwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "gdx" }

ashley = { module = "com.badlogicgames.ashley:ashley", version.ref = "ashley" }
artemis-odb = { module = "net.onedaybeard.artemis:artemis-odb", version.ref = "artemisOdb" }
vis-ui = { module = "com.kotcrab.vis:vis-ui", version.ref = "visUi" }
textra-typist = { module = "com.github.tommyettinger:textratypist", version.ref = "textraTypist" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
wiremock = { module = "com.github.tomakehurst:wiremock", version.ref = "wireMock" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlintest = { module = "io.kotlintest:kotlintest", version.ref = "kotlintest" }
spek-api = { module = "org.jetbrains.spek:spek-api", version.ref = "spek" }
spek-junit-platform-engine = { module = "org.jetbrains.spek:spek-junit-platform-engine", version.ref = "spek" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }
free-port-finder = { module = "me.alexpanov:free-port-finder", version.ref = "freePortFinder" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }
maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
