name: publish-documentation

on:
  push:
    branches: [ master ]
    paths:
      - '**.kt'
      - '**.kts'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v7
      - name: JDK setup
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
      - name: Save version
        shell: bash
        run: |
          echo "KTX_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v6
      - name: Dokka
        run: ./gradlew :dokkaGenerate --no-configuration-cache
      - name: Publish GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/dokka/html
          commit-message: 'Documentation of KTX ${{ env.KTX_VERSION }}.'
